### ISSUE TITLE
Error: Too many reconnects

### ISSUE THREAD

**Issue by mandazi** [ytb2mp3/ytb2mp3#2]
```
$ ytb2mp3 https://www.youtube.com/watch?v=PimVw0LomLs
Downloading [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% | ETA: 0s | Runtime: {Downloading [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% | ETA: 0s | Runtime: 0s | Speed: 0 kbytes/secevents.js:167
      throw er; // Unhandled 'error' event
      ^

Error: Too many reconnects
    at doDownload (/usr/local/lib/node_modules/ytb2mp3/node_modules/ytdl-core/lib/index.js:108:26)
    at PassThrough.onend (/usr/local/lib/node_modules/ytb2mp3/node_modules/ytdl-core/lib/index.js:150:7)
    at PassThrough.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at doDownload (/usr/local/lib/node_modules/ytb2mp3/node_modules/ytdl-core/lib/index.js:108:12)
    at PassThrough.onend (/usr/local/lib/node_modules/ytb2mp3/node_modules/ytdl-core/lib/index.js:150:7)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I am not sure what is going on but I am getting this error now.

**Comment by mandazi** [comment]
> This is using an outdated version of ytdl-core btw. You can see in the package-lock.json file. The error still happens with the video above, but you should always be using the latest version or you might run into other errors.

https://github.com/fent/node-ytdl-core/issues/212#issuecomment-455385210

Is it possible to update to the latest?

**Comment by ytb2mp3** [comment]
Please check out the latest version `0.2.0`
